--DROP TABLE IF EXISTS EMPLOYEE;
--DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT(
    dept_id INTEGER PRIMARY KEY
,   name VARCHAR(20)
);

CREATE TABLE EMPLOYEE(
    emp_id INTEGER PRIMARY KEY
,   name VARCHAR(100)
,   dept_id INTEGER REFERENCES DEPARTMENT(dept_id)
);

DELETE FROM EMPLOYEE;
DELETE FROM DEPARTMENT;

INSERT INTO DEPARTMENT VALUES(1, 'SALES');
INSERT INTO DEPARTMENT VALUES(2, 'DEVELOP');

INSERT INTO EMPLOYEE VALUES(101, 'Y.Aragaki', 1);
INSERT INTO EMPLOYEE VALUES(102, 'R.Matsui', 1);
INSERT INTO EMPLOYEE VALUES(103, 'E.Ikuta', 2);
INSERT INTO EMPLOYEE VALUES(104, 'R.Sakurai', 2);

